version: "3"

services:
  client:
    container_name: client
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network

  server:
    container_name: server
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    restart: always
    ports:
      - 8000:8000
    env_file: .env
    networks:
      - app_network
    depends_on:
      database:
        condition: service_healthy

  database:
    container_name: database
    image: postgres
    restart: always
    volumes:
      - pg:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?error}
      - POSTGRES_USER=${POSTGRES_USER:?error}
      - POSTGRES_DB=${POSTGRES_DB:?error}
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

volumes:
  pg:

networks:
  app_network:
    driver: bridge
    external: true
